version: '3'
services:
  server:
    container_name: bwd_thuur_vandeplassche
    build:
      context: .
      dockerfile: ./config/docker/dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/server/
    links:
      - "database"
    depends_on:
      - "database"
    environment:
      NODE_ENV: development
      CONTEXT: docker
      MONGODB_USER: root
      MONGODB_DATABASE: bwd_eco_plan
      MONGODB_PASS: Passw0rd
      MONGODB_PORT: 27017
      PORT: 3000
    restart: always

  database:
    container_name: bwd_thuur_vandeplassche_database
    image: mongo:latest
    volumes:
      - ./db/:/var/lib/mongodb
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Passw0rd
      MONGODB_USER: eco_user
      MONGODB_DATABASE: bwd_eco_plan
      MONGODB_PASS: Passw0rd
